name: contact
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.5.3


dependencies:
  flutter:
    sdk: flutter
  google_speech: ^3.0.0
  record: ^5.0.1
  just_audio: ^0.9.46
  audioplayers: ^5.2.1
  path_provider: ^2.0.0
  permission_handler: ^11.4.0
  signature: ^5.0.0
  shared_preferences: ^2.0.8
  flutter_tts: ^3.8.5
  pdf: ^3.10.7
  open_file: ^3.3.2
  share_plus: ^7.2.1
  http: ^1.3.0
  flutter_dotenv: ^5.2.1
  google_sign_in: ^6.2.1
  image_picker: ^1.0.7
  animate_do: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.10

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_icon_padded.png"
  adaptive_icon_background: "#FFFFFF"  # 배경색 설정 가능
  adaptive_icon_foreground: "assets/app_icon_padded.png"  # 안드로이드 어댑티브 아이콘



flutter:

  uses-material-design: true
  fonts:
    - family: NanumGothic
      fonts:
        - asset: assets/fonts/NotoSans-Regular.ttf
        - asset: assets/fonts/NanumGothic-Regular.ttf
        - asset: assets/fonts/NotoSansCJKkr-Regular.otf
  assets:
    - assets/config.json
    - assets/voice_service_account.json
    - assets/google_logo.png
    - assets/images/
    - assets/splash_icon.png
    - .env
